kind: Secret
apiVersion: v1
metadata:
  name: example-annotation
  annotations:
    avp.kubernetes.io/path: "/v1/secret/data/first-secret"
type: Opaque
data:
  username: <username>
  password: <password>
